### ISSUE TITLE
installs openresty 1.5.11.1 

### ISSUE THREAD

**Issue by josephcclim** [priestjim/chef-openresty#18]
Hi!

I'm using the default.rb when running the cookbook but I see openresty 1.5.11.1 installed and running on a new box from opsworks and also seen in vagrant.
This the version of the cookbook I'm using.

    cookbook 'openresty', '~> 0.3.2'

When I tried to override the default value using a wrapper cookbook it would still download the 1.5.11.1 version and give me an error

    ==> default: Mixlib::ShellOut::ShellCommandFailed
    ==> default: ------------------------------------
    ==> default: Expected process to exit with [0], but received '1'
    ==> default: ---- Begin output of "bash"  "/tmp/chef-script20150112-1718-1sorznf" ----
    ==> default: STDOUT: 
    ==> default: STDERR: /tmp/chef-script20150112-1718-1sorznf: line 2: cd: ngx_openresty-1.7.7.1: No     such file or directory
    ==> default: ---- End output of "bash"  "/tmp/chef-script20150112-1718-1sorznf" ----
    ==> default: Ran "bash"  "/tmp/chef-script20150112-1718-1sorznf" returned 1
    ==> default: 
    ==> default: 
    ==> default: Resource Declaration: 

Am I missing something really obvious here?

**Comment by priestjim** [comment]
Try using the latest cookbook version from here using:

    cookbook 'openresty',           '~> 0.3.3', :github => 'priestjim/chef-openresty'

**Comment by josephcclim** [comment]
Thank you that worked!
