### ISSUE TITLE
Latest version 0.3.4 is not in chef supermarket

### ISSUE THREAD

**Issue by FrankZZ** [priestjim/chef-openresty#20]
The latest version of this cookbook on the chef supermarket is 0.3.2.
Can you push 0.3.4?

Thanks

**Comment by priestjim** [comment]
I literally have no idea and can't find documentation anywhere about how to upload/update a new version of a cookbook in the supermarket!

**Comment by FrankZZ** [comment]
Try this, https://docs.chef.io/knife_cookbook_site.html#share
How did you put 0.3.2 up there? 

Thanks for looking into this 

Frank

**Comment by priestjim** [comment]
The latest version was uploaded through the Community site. I've read all available documentation and I still can't find how I can authorize my public key to upload there.

**Comment by rmoriz** [comment]
You should be able to sign in with your existing login to https://www.chef.io/account/login and https://supermarket.chef.io/sign-in.

To change your password/API credentials, log into Chef's SSO at https://www.chef.io/account.

**Comment by hrak** [comment]
Could you also please add release tags in git for 0.3.2 - 0.3.5?

**Comment by priestjim** [comment]
I did for 0.3.5. If you need for the earlier ones, please let me know!

**Comment by ronaldtse** [comment]
0.3.5 is still not on the supermarket -- is it possible to add it there? thanks!

**Comment by priestjim** [comment]
Done! Figured it out :)

**Comment by ronaldtse** [comment]
Thank you!
