### ISSUE TITLE
Upgrade from 1.7.10.1 to 1.7.10.2 fails

### ISSUE THREAD

**Issue by TanmayaA** [priestjim/chef-openresty#22]
Openresty upgrade fails when I try attribute override in a wrapper recipe like this:
override['openresty']['source']['version']   = '1.7.10.2'
override['openresty']['source']['checksum']  = '5E8BEAFB7B32BA62FD34B323B2E9CF49884B4F0491FCCF189F0B88B3E25DD0E4'

You can see error here -> https://gist.github.com/TanmayaA/e1b0bd64515d5f208859

**Comment by priestjim** [comment]
The checksum should be in lower case! I'll update the cookbook.
