### ISSUE TITLE
Attributes can't be overrided from a wrapper cookbook

### ISSUE THREAD

**Issue by vdel26** [priestjim/chef-openresty#25]
I have created a cookbook that has this one as a dependency. Everything works fine but I can't seem to be able to override attributes following the approach described here: https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/

In particular my problem is with the `node['openresty']['source']['prefix']` attribute. In the attributes/default.rb of my cookbook I have:
`default['openresty']['source']['prefix'] = '/etc'`

But it is still deploying Nginx using the default value for that attribute, `/usr/share`. I even tried specified the attribute as:
`override['openresty']['source']['prefix'] = '/etc'`
but that didn't work either.

I was wondering if you had any idea of why that might be happening.
If I set the same attribute by passing it in my node.json description it works fine then.

Thanks!

**Comment by priestjim** [comment]
The second one is the correct way to do it (override). However, please bear in mind that if you override an attribute, all attributes that depend on that will not automatically be updated, so you'll need to update those as well.
