### ISSUE TITLE
Request: Custom Error Pages

### ISSUE THREAD

**Issue by hulu1522** [priestjim/chef-openresty#26]
It would be nice to be able to declare (either by attribute or LWRP) custom error pages.  Then all we would have to do is include the file in our cookbooks and specify the source.  Openresty cookbook would then copy them where it wants and put the entries for it into the config.

**Comment by priestjim** [comment]
Error pages are something that is usually unique to an app/installation, so an LWRP would be kind of overkill here.

**Comment by hulu1522** [comment]
Okay thanks.
