### ISSUE TITLE
Include conf.d/*.conf outside of nginx.conf http block

### ISSUE THREAD

**Issue by jdp** [priestjim/chef-openresty#30]
It would be great if conf.d/*.conf was included outside of the default nginx.conf's http block. [Here is the relevant section](https://github.com/priestjim/chef-openresty/blob/master/templates/default/nginx.conf.erb#L100). That way other config files could be included without having to completely overwrite/customize nginx.conf, because some directives aren't allowed inside of http blocks.

**Comment by priestjim** [comment]
If I include the conf.d files outside of the http block then transparently including files will no longer work :/
