### ISSUE TITLE
Cookbook failure on libatomic_ops on RHEL7

### ISSUE THREAD

**Issue by ealliaume** [priestjim/chef-openresty#31]
Got an error when using this cookbook.
It fails to install the package "libatomic_ops-devel" declared in openresty/recipes/commons_build.rb

Installed on ec2 with the AMI "Red Hat Enterprise Linux 7.2 (HVM), SSD Volume Type - ami-e0c19f83"
## Chef::Exceptions::Package

No candidate version available for libatomic_ops-devel
yum_package("libatomic_ops-devel") do
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
package_name "libatomic_ops-devel"
flush_cache {:before=>false, :after=>false}
declared_type :package
cookbook_name :openresty
recipe_name "commons_build"
end

**Comment by priestjim** [comment]
What does a `yum search atomic` return in terms of package names? I have a feeling they renamed the package on RHEL 7.

**Comment by ealliaume** [comment]
Seems to be the same name

[ec2-user@ip-172-31-5-209 ~]$ sudo yum search atomic
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
===================================================================================== N/S matched: atomic ======================================================================================
boost-atomic.i686 : Run-Time component of boost atomic library
boost-atomic.x86_64 : Run-Time component of boost atomic library
libatomic.i686 : The GNU Atomic library
libatomic.x86_64 : The GNU Atomic library
libatomic-static.i686 : The GNU Atomic static library
libatomic-static.x86_64 : The GNU Atomic static library
libatomic_ops-devel.x86_64 : Atomic memory update operations

**Comment by priestjim** [comment]
Chef version? Is the yum cache populated?

**Comment by priestjim** [comment]
Closed as inactive
