### ISSUE TITLE
Why not use the chef nginx cookbooks upstart script?

### ISSUE THREAD

**Issue by ccleung** [priestjim/chef-openresty#35]
I am wondering what are the key differences between the upstart script supplied by by this cookbook https://github.com/priestjim/chef-openresty/blob/master/templates/ubuntu/nginx.init.erb, and the upstart script in the nginx chef recipe: https://github.com/miketheman/nginx/blob/3.0.0-rewrite/templates/default/sysvinit/nginx.erb

They look somewhat similar to me. Would it be beneficial to make `chef-openresty` dependent on `nginx` chef recipe?

I see that the `nginx.conf` is more comprehensive to support openresty lua in this repo: https://github.com/priestjim/chef-openresty/blob/master/templates/default/nginx.conf.erb vs https://github.com/miketheman/nginx/blob/3.0.0-rewrite/templates/default/nginx.conf.erb which is quite basic, perhaps thats the reason to not depend on the `ngnix` chef recipe?

**Comment by keen99** [comment]
currently, the nginx cookbook's default branch (3.0.0-rewrite) is a "work in progress" and, at least in my eyes, not ready to be used.

I spent yesterday trying to get that cookbook (both 3.0.0 and 2.7.6) to install and compile openresty and gave up after I found the openresty cookbook. :)

I can't speak to the upstart/init script though - but I wouldn't vote for building on top of the nginx cookbook in the immediate future.

**Comment by priestjim** [comment]
I deliberately diverged from the nginx cookbook for a lot of reasons:
- the nginx cookbook includes features like passenger which do not really resonate with the crowd openresty is aimed for
- I had more liberty to implement features of daring stability for general consumption (although they work perfectly) such as the automatic CPU affinity calculation and the more elaborate nginx.conf
- the complexity and variety of modules you can build/include with openresty with its default bundle is so great that it would pollute the vanilla nginx cookbook a lot

I'll be backporting the newer nginx upstart script though. Looks cleaner.
