### ISSUE TITLE
Please update version when merging new changes

### ISSUE THREAD

**Issue by gwilton** [priestjim/chef-openresty#40]
One of these changes broken our builds and we had the cookbook pinned to 0.3.5

```
Commits on Feb 22, 2016
@priestjim
Version bump for OpenResty
priestjim committed 17 hours ago
7773955  
@priestjim
Merge pull request #39 from kuberkaul/master  …
priestjim committed 17 hours ago
bc81aad  
@kuberkaul
update the nginx-upstream-fair github link from SSH to HTTPS  …
kuberkaul committed a day ago
```

**Comment by priestjim** [comment]
Probably the directory name change in the newest version of OR. I'd suggest pinning to the supermarket package instead of the github repo OR pinning to the github repo tag

**Comment by gwilton** [comment]
Thanks.

Changed our pinning to the following,  as we needed some of the changes in January. Thanks!

cookbook 'openresty', git: 'git@github.com:priestjim/chef-openresty.git', ref: '3e9385c38072da9855956165516c6a431468a0e0'

**Comment by priestjim** [comment]
I'm pretty sure you can use the latest release if you set node['openresty']['name'] to 'ngx_openresty' instead of 'openresty' in case you're just using an older OpenResty release
