### ISSUE TITLE
chef_version in metadata.rb causes trouble on AWS OpsWorks

### ISSUE THREAD

**Issue by madeddie** [priestjim/chef-openresty#41]
The adding of chef_version to metadata in tag 0.4.0 doesn't sit well with the Berkshelf used bij AWS OpsWorks when using Chef 11.04

The Chef run now fails.

```
[2016-02-24T11:05:42+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/openresty into a Chef object: undefined method `chef_version' for #<Chef::Cookbook::Metadata:0x007f8287ddd7e8>
```

See also: berkshelf/berkshelf#1499

**Comment by priestjim** [comment]
Have you tried with a newer Chef version? http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11.html

**Comment by madeddie** [comment]
Yes, it's specifically a problem with Chef 11.04 (on OpsWorks).
The only options for Linux are 11.04 with Berkshelf or 12 without Berkshelf.

I assume quite a lot of organisations will stay on Chef 11.04 for a while, because the way it works with 12 is a hassle to get deployment systems fixed to. (you need to `berks package` all needed cookbooks and put them somewhere online to be downloaded during the OpsWorks Chef run).

That said, I'm almost done migrating to 12 with all my stacks, so it's not a problem for me, just a problem I thought you should be aware of.

**Comment by priestjim** [comment]
I see your point! I appreciate the feedback, I only put these lines there to make the supermarket page more elaborate (this is where all this extra metadata appear)

**Comment by madeddie** [comment]
Yeah, makes sense. In most situations I'd advice people to just try to use the newest stable releases of software, but yeah, S/P/IaaS... :)

Feel free to close the issue

**Comment by madeddie** [comment]
As a last comment, this fix is used by others for the same sort of problems:

https://github.com/st-isidore-de-seville/cookbook-apt-docker/pull/6/files

**Comment by priestjim** [comment]
@madeddie I like it, I'm gonna use it!

**Comment by marzzz21** [comment]
I'm getting this problem as well on an on-premise Chef:
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0

**Comment by priestjim** [comment]
I've updated the supermarket version to include respond_? so it should be working fine now!

**Comment by madeddie** [comment]
Also my problem was quite specific to chef11 and the berkshelf version used on OpsWorks.
Chef12 with any berks version 4+ doesn't have this same problem.

Another maybe, but in that case, it'd be best to open new ticket and give some logging output

**Comment by priestjim** [comment]
As I said, the issue is resolved with respond_to? both in the lateset commit and the latest version uploaded to supermarket.
