### ISSUE TITLE
delayed interpolation issues with attributes

### ISSUE THREAD

**Issue by keen99** [priestjim/chef-openresty#49]
the new default['openresty']['source']['name'] attribute introduced in 0.4.0, as well as the default['openresty']['source']['url'] attribute suffer from delayed interpolation problems (see https://coderanger.net/derived-attributes/ for reference) - 

specifically, if I specify just the ['version'] attribute, the ['url'] and ['name'] atrtributes don't change:

This results in cases like:

``` STDERR: /tmp/chef-script20160520-16429-z5r8oj: line 2: cd: openresty-1.9.7.3: No such file or directory
---- End output of "bash"  "/tmp/chef-script20160520-16429-z5r8oj" ---- ```

if you only set 
```
node.override['openresty']['source']['version']="1.9.3.2"
#must set both due to lack of delayed interpolation
node.override['openresty']['source']['url']="https://openresty.org/download/ngx_openresty-#{node['openresty']['source']['version']}.tar.gz"
```

for example - we fetch 1.9.3.2, but ['name'] is still 1.9.7.3.


Anyway - poor explaination but I'm going to try to effect a fix (using %{} - which effects all consumers of the attr..)

**Comment by priestjim** [comment]
This issue actually exists in many projects, using delayed interpolation should fix it! Either shoot a PR or I'll fix it myself in a couple of days :) Thanks!
