### ISSUE TITLE
openresty_luarock provider reinstalls luarocks with full version

### ISSUE THREAD

**Issue by gregkare** [priestjim/chef-openresty#63]
We found out (because luarocks was down) that the openresty_luarock provider was trying to install a luarock even though it was already installed in the right version.

This line of code is responsible for this behavior: https://github.com/priestjim/chef-openresty/blob/d4362c79790320e910030a3f28e44558360ed28a/providers/luarock.rb#L34. It returns "2.1.0" when the current version is "2.1.0-1", and thus the provider will install the same luarock again.

Is this expected behavior? Are we supposed to pass versions without the revision number?

Thanks

**Comment by priestjim** [comment]
I've updated the cookbook to consider the revision of the installed rock if you specify a revision yourself.

**Comment by gregkare** [comment]
Thanks!
