### ISSUE TITLE
Consider loosening `ohai` version

### ISSUE THREAD

**Issue by 198d** [priestjim/chef-openresty#66]
In 00036f6, you tightened the `ohai` constraint and I don't understand why. Flipping through the issue mentioned in the commit message, there's talk of the Ohai gem, but nothing about the cookbook. I am using the `openresty` cookbook in Chef environments that have their `ohai` cookbook version pinned at `>= 5.0.0` which doesn't seem to cause any issues with `openresty` at `0.5.5`. Would you consider loosening it again?

**Comment by dorongutman** [comment]
@priestjim can you please address this ? the ohai gem has been updated with some needed stuff and this constraint blocks it

**Comment by priestjim** [comment]
In theory, the optimistic operator should allow the `ohai` cookbook to be used with version 5.0. I don't think I had a specific reason to pin it to 4.1 so I updated it and the tests work fine.
