### ISSUE TITLE
PCRE Binary currently failing from SourceForge

### ISSUE THREAD

**Issue by SimonKaluza** [priestjim/chef-openresty#67]
Looks like SourceForge is currently in "disaster recovery" mode and won't let the cookbook download the binaries, thus failing the checksum match.

This can be confirmed by running `wget https://sourceforge.net/projects/pcre/files/pcre/8.38/pcre-8.38.tar.bz2/download` which pulls a HTML file instead of the correct binaries.

Maybe we should use a different host to grab PCRE from?

**Comment by priestjim** [comment]
It looks like it's back online now.

**Comment by SimonKaluza** [comment]
That's true!  Maybe it was a temporary outage.  I may use the branch that uses the old URL as it seems the PCRE maintainer FTP allows anonymous http access again at https://ftp.pcre.org/pub/pcre/

**Comment by priestjim** [comment]
I believe SF has a lot more hands and is more reliable when it comes to using it as a file host so I'll continue using it in this repo.
