### ISSUE TITLE
Error executing action `restart` on resource 'service[nginx]'

### ISSUE THREAD

**Issue by sngo09** [priestjim/chef-openresty#78]
Hi,
I don't understand why I have this error. I just want to install the latest version of openresty with a simple include_recipe. (see attached file)

![capture du 2018-07-09 17-14-33](https://user-images.githubusercontent.com/38039220/42459285-aefb786a-839b-11e8-86cf-3ddd141104f0.png)
Thank you for helping me !

Regards,
Stephane

**Comment by priestjim** [comment]
Hey Stephane,

There is probably an error occurring before this and Chef is trying to notify the service before actually installing it, erroring out and overriding the actual error that made the chef run crash. This actually made this cookbook's CentOS tests fail as it didn't have the SSL dependency installed. Maybe this was your issue too, so I suggest trying with the latest code from this repository!
